const PEN_WIDTH = 20;
const NOT_FOUND = -1;
const CANVAS_WIDTH = 640;
const CANVAS_HEIGHT = 480;
const HTTP_STATUS_CREATED = 201;
const HTTP_STATUS_BAD_REQUEST = 400;
const MILLISECOND_TO_SECONDS = 1000;
const QUARTER_SECOND = 250;
const MINUTE_TO_SECONDS = 60;
const CLEAN_USERNAME = -2;

export { PEN_WIDTH, NOT_FOUND, CANVAS_HEIGHT, CANVAS_WIDTH, CLEAN_USERNAME };
export { HTTP_STATUS_CREATED, HTTP_STATUS_BAD_REQUEST };
export { MILLISECOND_TO_SECONDS, QUARTER_SECOND, MINUTE_TO_SECONDS };
